
services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: ld1d2md12km20dkm
    ports:
        - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: 
